#!/usr/bin/env python3

import sys,os

print(r"""\RequirePackage{luatex85}\documentclass[%(mode)s,xcolor={table,rgb,dvipsnames}]{beamer}
\input{preamble}
\input{%(OL_DIR)s/preamble}
\begin{document}
\input{%(src)s}
\end{document}"""%(
    dict(mode=sys.argv[1],
         OL_DIR=os.environ.get("OL_DIR", ""),
         src=sys.argv[2])
))
